import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard', plans: 'Plans & Payment', logout: 'Logout', worker: 'Worker',
    signIn: 'Sign In', workerPortal: 'Worker Portal',
    tagline: 'Risk aaye, Coverly bachaye',
    taglineSub: 'Sign in to access your coverage, live conditions, and claim history.',
    phoneNumber: 'Phone Number', password: 'Password',
    enterPhone: 'Enter your phone number', enterPassword: 'Enter your password',
    signingIn: 'Signing in...', newToApp: 'New to Coverly?', createAccount: 'Create account',
    adminUser: 'Admin user?', adminLogin: 'Admin login →',
    trustedBy: 'Trusted by 10M+ gig workers',
    instantPayouts: 'Instant Payouts', maxCoverage: 'Max Coverage', startingFrom: 'Starting From',
    welcomeMsg: 'Welcome back', riskScore: 'Risk Score', weeklyPremium: 'Weekly Premium',
    earningsProtected: 'Earnings Protected', totalPaidOut: 'Total Paid Out',
    activatePolicy: 'Activate Policy', riskProfile: 'Risk Profile', aiComputed: 'AI-computed assessment',
    policyActive: 'Policy Active', noActivePolicy: 'No Active Policy', viewPlans: 'View Plans',
    claimsHistory: 'Claims History', liveConditions: 'Live Conditions',
    createAcc: 'Create Account', joinToday: 'Join Coverly today',
    fullName: 'Full Name', city: 'City', pinCode: 'PIN Code', weeklyHours: 'Weekly Hours',
    platform: 'Platform', riderId: 'Rider ID', riderIdPlaceholder: 'e.g. ZPT-12345',
    registerBtn: 'Register & Get Insured', alreadyReg: 'Already registered?',
    close: 'Close', loading: 'Loading...', dynamicPricing: 'Dynamic ML pricing',
    thisWeek: 'This week', claimsFiled: 'claims filed',
    bonusDashboard: 'Bonus Dashboard', faqs: 'FAQs', customerCare: 'Customer Care',
    burnoutAlert: 'Burnout Alert', platformDowntime: 'Platform Downtime',
  },
  hi: {
    dashboard: 'डैशबोर्ड', plans: 'योजनाएं और भुगतान', logout: 'लॉग आउट', worker: 'कर्मचारी',
    signIn: 'साइन इन', workerPortal: 'वर्कर पोर्टल',
    tagline: 'रिस्क आए, Coverly बचाए',
    taglineSub: 'अपनी कवरेज, लाइव स्थितियां और दावा इतिहास देखने के लिए साइन इन करें।',
    phoneNumber: 'फ़ोन नंबर', password: 'पासवर्ड',
    enterPhone: 'अपना फ़ोन नंबर दर्ज करें', enterPassword: 'अपना पासवर्ड दर्ज करें',
    signingIn: 'साइन इन हो रहा है...', newToApp: 'Coverly में नए हैं?', createAccount: 'खाता बनाएं',
    adminUser: 'एडमिन यूज़र?', adminLogin: 'एडमिन लॉगिन →',
    trustedBy: '1 करोड़+ गिग वर्कर्स का भरोसा',
    instantPayouts: 'तुरंत भुगतान', maxCoverage: 'अधिकतम कवरेज', startingFrom: 'शुरुआत से',
    welcomeMsg: 'वापसी पर स्वागत', riskScore: 'जोखिम स्कोर', weeklyPremium: 'साप्ताहिक प्रीमियम',
    earningsProtected: 'सुरक्षित आय', totalPaidOut: 'कुल भुगतान',
    activatePolicy: 'पॉलिसी सक्रिय करें', riskProfile: 'जोखिम प्रोफ़ाइल', aiComputed: 'AI-आधारित मूल्यांकन',
    policyActive: 'पॉलिसी सक्रिय', noActivePolicy: 'कोई सक्रिय पॉलिसी नहीं', viewPlans: 'योजनाएं देखें',
    claimsHistory: 'दावा इतिहास', liveConditions: 'लाइव स्थितियां',
    createAcc: 'खाता बनाएं', joinToday: 'आज Coverly से जुड़ें',
    fullName: 'पूरा नाम', city: 'शहर', pinCode: 'पिन कोड', weeklyHours: 'साप्ताहिक घंटे',
    platform: 'प्लेटफ़ॉर्म', riderId: 'राइडर आईडी', riderIdPlaceholder: 'जैसे ZPT-12345',
    registerBtn: 'रजिस्टर करें और बीमा पाएं', alreadyReg: 'पहले से रजिस्टर्ड हैं?',
    close: 'बंद करें', loading: 'लोड हो रहा है...', dynamicPricing: 'डायनामिक ML मूल्य निर्धारण',
    thisWeek: 'इस सप्ताह', claimsFiled: 'दावे दर्ज',
    bonusDashboard: 'बोनस डैशबोर्ड', faqs: 'सामान्य प्रश्न', customerCare: 'ग्राहक सेवा',
    burnoutAlert: 'बर्नआउट अलर्ट', platformDowntime: 'प्लेटफ़ॉर्म डाउनटाइम',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு', plans: 'திட்டங்கள் & கட்டணம்', logout: 'வெளியேறு', worker: 'தொழிலாளர்',
    signIn: 'உள்நுழைய', workerPortal: 'வொர்க்கர் போர்டல்',
    tagline: 'ரிஸ்க் வந்தால், Coverly காக்கும்',
    taglineSub: 'உங்கள் கவரேஜ், நேரடி நிலைமைகள் மற்றும் கோரல் வரலாற்றை அணுக உள்நுழையவும்.',
    phoneNumber: 'தொலைபேசி எண்', password: 'கடவுச்சொல்',
    enterPhone: 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்', enterPassword: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    signingIn: 'உள்நுழைகிறது...', newToApp: 'Coverly-ல் புதியவரா?', createAccount: 'கணக்கு உருவாக்கு',
    adminUser: 'நிர்வாகி?', adminLogin: 'நிர்வாகி உள்நுழைவு →',
    trustedBy: '1 கோடி+ கிக் தொழிலாளர்களின் நம்பிக்கை',
    instantPayouts: 'உடனடி கட்டணம்', maxCoverage: 'அதிகபட்ச கவரேஜ்', startingFrom: 'தொடங்கி',
    welcomeMsg: 'மீண்டும் வரவேற்கிறோம்', riskScore: 'ரிஸ்க் ஸ்கோர்', weeklyPremium: 'வாராந்திர பிரீமியம்',
    earningsProtected: 'பாதுகாக்கப்பட்ட வருமானம்', totalPaidOut: 'மொத்த கட்டணம்',
    activatePolicy: 'பாலிசி செயல்படுத்து', riskProfile: 'ரிஸ்க் புரொஃபைல்', aiComputed: 'AI கணக்கீடு',
    policyActive: 'பாலிசி செயலில் உள்ளது', noActivePolicy: 'செயலில் பாலிசி இல்லை', viewPlans: 'திட்டங்களை காண்க',
    claimsHistory: 'கோரல் வரலாறு', liveConditions: 'நேரடி நிலைமைகள்',
    createAcc: 'கணக்கு உருவாக்கு', joinToday: 'இன்று Coverly-ல் சேரவும்',
    fullName: 'முழு பெயர்', city: 'நகரம்', pinCode: 'பின் குறியீடு', weeklyHours: 'வாராந்திர மணிநேரம்',
    platform: 'தளம்', riderId: 'ரைடர் ஐடி', riderIdPlaceholder: 'எ.கா. ZPT-12345',
    registerBtn: 'பதிவு செய்து காப்பீடு பெறுங்கள்', alreadyReg: 'ஏற்கனவே பதிவு செய்தீர்களா?',
    close: 'மூடு', loading: 'ஏற்றுகிறது...', dynamicPricing: 'டைனமிக் ML விலை நிர்ணயம்',
    thisWeek: 'இந்த வாரம்', claimsFiled: 'கோரல்கள் தாக்கல்',
    bonusDashboard: 'போனஸ் டாஷ்போர்டு', faqs: 'அடிக்கடி கேட்கப்படும் கேள்விகள்', customerCare: 'வாடிக்கையாளர் சேவை',
    burnoutAlert: 'பர்ன்அவுட் எச்சரிக்கை', platformDowntime: 'பிளாட்ஃபார்ம் டவுன்டைம்',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড', plans: 'পরিকল্পনা ও পেমেন্ট', logout: 'লগ আউট', worker: 'কর্মী',
    signIn: 'সাইন ইন', workerPortal: 'ওয়ার্কার পোর্টাল',
    tagline: 'ঝুঁকি এলে, Coverly বাঁচায়',
    taglineSub: 'আপনার কভারেজ, লাইভ অবস্থা এবং দাবির ইতিহাস দেখতে সাইন ইন করুন।',
    phoneNumber: 'ফোন নম্বর', password: 'পাসওয়ার্ড',
    enterPhone: 'আপনার ফোন নম্বর লিখুন', enterPassword: 'আপনার পাসওয়ার্ড লিখুন',
    signingIn: 'সাইন ইন হচ্ছে...', newToApp: 'Coverly-তে নতুন?', createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    adminUser: 'অ্যাডমিন ব্যবহারকারী?', adminLogin: 'অ্যাডমিন লগইন →',
    trustedBy: '১ কোটি+ গিগ কর্মীর বিশ্বাস',
    instantPayouts: 'তাৎক্ষণিক পেমেন্ট', maxCoverage: 'সর্বোচ্চ কভারেজ', startingFrom: 'শুরু থেকে',
    welcomeMsg: 'ফিরে আসায় স্বাগতম', riskScore: 'ঝুঁকি স্কোর', weeklyPremium: 'সাপ্তাহিক প্রিমিয়াম',
    earningsProtected: 'সুরক্ষিত আয়', totalPaidOut: 'মোট পেমেন্ট',
    activatePolicy: 'পলিসি সক্রিয় করুন', riskProfile: 'ঝুঁকি প্রোফাইল', aiComputed: 'AI-গণনা করা মূল্যায়ন',
    policyActive: 'পলিসি সক্রিয়', noActivePolicy: 'কোনো সক্রিয় পলিসি নেই', viewPlans: 'পরিকল্পনা দেখুন',
    claimsHistory: 'দাবির ইতিহাস', liveConditions: 'লাইভ অবস্থা',
    createAcc: 'অ্যাকাউন্ট তৈরি করুন', joinToday: 'আজই Coverly-তে যোগ দিন',
    fullName: 'পুরো নাম', city: 'শহর', pinCode: 'পিন কোড', weeklyHours: 'সাপ্তাহিক ঘণ্টা',
    platform: 'প্ল্যাটফর্ম', riderId: 'রাইডার আইডি', riderIdPlaceholder: 'যেমন ZPT-12345',
    registerBtn: 'নিবন্ধন করুন ও বীমা পান', alreadyReg: 'ইতিমধ্যে নিবন্ধিত?',
    close: 'বন্ধ করুন', loading: 'লোড হচ্ছে...', dynamicPricing: 'ডায়নামিক ML মূল্য নির্ধারণ',
    thisWeek: 'এই সপ্তাহ', claimsFiled: 'দাবি দাখিল',
    bonusDashboard: 'বোনাস ড্যাশবোর্ড', faqs: 'সাধারণ প্রশ্ন', customerCare: 'গ্রাহক সেবা',
    burnoutAlert: 'বার্নআউট সতর্কতা', platformDowntime: 'প্ল্যাটফর্ম ডাউনটাইম',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ', plans: 'ਯੋਜਨਾਵਾਂ ਅਤੇ ਭੁਗਤਾਨ', logout: 'ਲੌਗ ਆਊਟ', worker: 'ਕਾਮਾ',
    signIn: 'ਸਾਈਨ ਇਨ', workerPortal: 'ਵਰਕਰ ਪੋਰਟਲ',
    tagline: 'ਰਿਸਕ ਆਵੇ, Coverly ਬਚਾਵੇ',
    taglineSub: 'ਆਪਣੀ ਕਵਰੇਜ, ਲਾਈਵ ਹਾਲਾਤ ਅਤੇ ਦਾਅਵੇ ਦਾ ਇਤਿਹਾਸ ਦੇਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।',
    phoneNumber: 'ਫ਼ੋਨ ਨੰਬਰ', password: 'ਪਾਸਵਰਡ',
    enterPhone: 'ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ', enterPassword: 'ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
    signingIn: 'ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...', newToApp: 'Coverly ਵਿੱਚ ਨਵੇਂ ਹੋ?', createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    adminUser: 'ਐਡਮਿਨ ਯੂਜ਼ਰ?', adminLogin: 'ਐਡਮਿਨ ਲੌਗਿਨ →',
    trustedBy: '1 ਕਰੋੜ+ ਗਿਗ ਵਰਕਰਾਂ ਦਾ ਭਰੋਸਾ',
    instantPayouts: 'ਤੁਰੰਤ ਭੁਗਤਾਨ', maxCoverage: 'ਵੱਧ ਤੋਂ ਵੱਧ ਕਵਰੇਜ', startingFrom: 'ਸ਼ੁਰੂਆਤ ਤੋਂ',
    welcomeMsg: 'ਵਾਪਸੀ ਤੇ ਜੀ ਆਇਆਂ', riskScore: 'ਜੋਖਮ ਸਕੋਰ', weeklyPremium: 'ਹਫ਼ਤਾਵਾਰੀ ਪ੍ਰੀਮੀਅਮ',
    earningsProtected: 'ਸੁਰੱਖਿਅਤ ਕਮਾਈ', totalPaidOut: 'ਕੁੱਲ ਭੁਗਤਾਨ',
    activatePolicy: 'ਪਾਲਿਸੀ ਸਰਗਰਮ ਕਰੋ', riskProfile: 'ਜੋਖਮ ਪ੍ਰੋਫਾਈਲ', aiComputed: 'AI-ਆਧਾਰਿਤ ਮੁਲਾਂਕਣ',
    policyActive: 'ਪਾਲਿਸੀ ਸਰਗਰਮ', noActivePolicy: 'ਕੋਈ ਸਰਗਰਮ ਪਾਲਿਸੀ ਨਹੀਂ', viewPlans: 'ਯੋਜਨਾਵਾਂ ਦੇਖੋ',
    claimsHistory: 'ਦਾਅਵੇ ਦਾ ਇਤਿਹਾਸ', liveConditions: 'ਲਾਈਵ ਹਾਲਾਤ',
    createAcc: 'ਖਾਤਾ ਬਣਾਓ', joinToday: 'ਅੱਜ Coverly ਨਾਲ ਜੁੜੋ',
    fullName: 'ਪੂਰਾ ਨਾਮ', city: 'ਸ਼ਹਿਰ', pinCode: 'ਪਿੰਨ ਕੋਡ', weeklyHours: 'ਹਫ਼ਤਾਵਾਰੀ ਘੰਟੇ',
    platform: 'ਪਲੇਟਫਾਰਮ', riderId: 'ਰਾਈਡਰ ਆਈਡੀ', riderIdPlaceholder: 'ਜਿਵੇਂ ZPT-12345',
    registerBtn: 'ਰਜਿਸਟਰ ਕਰੋ ਅਤੇ ਬੀਮਾ ਪਾਓ', alreadyReg: 'ਪਹਿਲਾਂ ਤੋਂ ਰਜਿਸਟਰਡ ਹੋ?',
    close: 'ਬੰਦ ਕਰੋ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...', dynamicPricing: 'ਡਾਇਨਾਮਿਕ ML ਕੀਮਤ',
    thisWeek: 'ਇਸ ਹਫ਼ਤੇ', claimsFiled: 'ਦਾਅਵੇ ਦਰਜ',
    bonusDashboard: 'ਬੋਨਸ ਡੈਸ਼ਬੋਰਡ', faqs: 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ', customerCare: 'ਗਾਹਕ ਸੇਵਾ',
    burnoutAlert: 'ਬਰਨਆਊਟ ਅਲਰਟ', platformDowntime: 'ਪਲੇਟਫਾਰਮ ਡਾਊਨਟਾਈਮ',
  },
  mr: {
    dashboard: 'डॅशबोर्ड', plans: 'योजना आणि पेमेंट', logout: 'लॉग आउट', worker: 'कामगार',
    signIn: 'साइन इन', workerPortal: 'वर्कर पोर्टल',
    tagline: 'धोका आला, Coverly वाचवेल',
    taglineSub: 'तुमचे कव्हरेज, लाइव्ह परिस्थिती आणि दाव्याचा इतिहास पाहण्यासाठी साइन इन करा.',
    phoneNumber: 'फोन नंबर', password: 'पासवर्ड',
    enterPhone: 'तुमचा फोन नंबर टाका', enterPassword: 'तुमचा पासवर्ड टाका',
    signingIn: 'साइन इन होत आहे...', newToApp: 'Coverly मध्ये नवीन आहात?', createAccount: 'खाते तयार करा',
    adminUser: 'अॅडमिन यूजर?', adminLogin: 'अॅडमिन लॉगिन →',
    trustedBy: '1 कोटी+ गिग कामगारांचा विश्वास',
    instantPayouts: 'त्वरित पेमेंट', maxCoverage: 'जास्तीत जास्त कव्हरेज', startingFrom: 'सुरुवातीपासून',
    welcomeMsg: 'परत आल्याबद्दल स्वागत', riskScore: 'जोखीम स्कोर', weeklyPremium: 'साप्ताहिक प्रीमियम',
    earningsProtected: 'सुरक्षित कमाई', totalPaidOut: 'एकूण पेमेंट',
    activatePolicy: 'पॉलिसी सक्रिय करा', riskProfile: 'जोखीम प्रोफाइल', aiComputed: 'AI-आधारित मूल्यांकन',
    policyActive: 'पॉलिसी सक्रिय', noActivePolicy: 'कोणतीही सक्रिय पॉलिसी नाही', viewPlans: 'योजना पहा',
    claimsHistory: 'दाव्याचा इतिहास', liveConditions: 'लाइव्ह परिस्थिती',
    createAcc: 'खाते तयार करा', joinToday: 'आज Coverly मध्ये सामील व्हा',
    fullName: 'पूर्ण नाव', city: 'शहर', pinCode: 'पिन कोड', weeklyHours: 'साप्ताहिक तास',
    platform: 'प्लॅटफॉर्म', riderId: 'रायडर आयडी', riderIdPlaceholder: 'उदा. ZPT-12345',
    registerBtn: 'नोंदणी करा आणि विमा मिळवा', alreadyReg: 'आधीच नोंदणी केली आहे?',
    close: 'बंद करा', loading: 'लोड होत आहे...', dynamicPricing: 'डायनामिक ML किंमत',
    thisWeek: 'या आठवड्यात', claimsFiled: 'दावे दाखल',
    bonusDashboard: 'बोनस डॅशबोर्ड', faqs: 'वारंवार विचारले जाणारे प्रश्न', customerCare: 'ग्राहक सेवा',
    burnoutAlert: 'बर्नआउट अलर्ट', platformDowntime: 'प्लॅटफॉर्म डाउनटाइम',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export const LANGUAGES = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'hi', label: 'हि', name: 'हिंदी' },
  { code: 'ta', label: 'த', name: 'தமிழ்' },
  { code: 'bn', label: 'বা', name: 'বাংলা' },
  { code: 'pa', label: 'ਪੰ', name: 'ਪੰਜਾਬੀ' },
  { code: 'mr', label: 'म', name: 'मराठी' },
];
